name: Build and Release
run-name: ${{ github.workflow }} for ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
        clang-version: [20.1.4]
        include:
          - os: ubuntu-latest
            platform: linux
            python-version: "3.13"
            nuitka: true
          - os: windows-latest
            platform: windows
            python-version: "3.12"   # https://github.com/Nuitka/Nuitka/issues/3234
            nuitka: false   # AttributeError: 'ListAction' object has no attribute 'replace'
          - os: macos-15
            platform: macos
            python-version: "3.13"
            nuitka: true
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        if: ${{ matrix.nuitka }}
        with:
          version: ${{ matrix.clang-version }}

      - name: Install Linux system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update --fix-missing && sudo apt install -y patchelf lld

      - name: Set SDKROOT on macOS
        if: matrix.os == 'macos-15'
        run: echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.14"
          enable-cache: false

      - name: Install dependencies with uv
        run: uv sync --all-groups

      - name: Run build script
        shell: bash
        run: |
            if [[ "${{ matrix.nuitka }}" == "true" ]]; then
              uv run build.py --nuitka --clang
            else
              uv run build.py
            fi

      - name: Make binaries executable
        if: matrix.os == 'macos-15' || matrix.os == 'ubuntu-latest'
        run: chmod +x ./dist/spectroterm || true

      - name: Archive files
        shell: bash
        run: |
          version=${GITHUB_REF#refs/tags/}
          extra="README.md LICENSE"
          cd dist
          cp ../{README.md,LICENSE,commands.md,configuration.md} .
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            tar -czf "spectroterm-$version-${{ matrix.platform }}.tar.gz" spectroterm $extra
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a "spectroterm-$version-${{ matrix.platform }}.zip" spectroterm.exe $extra
          else
            zip "spectroterm-$version-${{ matrix.platform }}.zip" spectroterm $extra
          fi
          cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            ./dist/*.zip
            ./dist/*.tar.gz
          compression-level: 0

      - name: Delete previous workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
          delete_workflow_pattern: build-and-release


  draft-release:
    name: Draft GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
          merge-multiple: true

      - name: Extract version from tag
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate release attestation
        uses: actions/attest-build-provenance@v2.4.0
        with:
          subject-path: "dist/*"

      - name: Draft a release
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ steps.extract_version.outputs.version }} [DRAFTED BY CI]'
          tag_name: '${{ steps.extract_version.outputs.version }}'
          target_commitish: ${{ github.sha }}
          draft: true
          prerelease: ${{ contains(steps.extract_version.outputs.version, 'dev') }}
          files: dist/*
          generate_release_notes: true
